baseURL: https://jedrzej.lewandowski.doctor/
defaultContentLanguage: en
theme: jblew-on-cupper-hugo-theme
enableGitInfo: true

taxonomies:
  category: category
  tag: tags

languages:
  pl:
    languageName: Polski
    title: Jędrzej Lewandowski (J-J) — programista i student medycyny
    header:
      supertitle: Ciekawe przypadki
      midtitle1: Jędrzeja
      midtitle2: Lewandowskiego
      subtitle: Programista, może będę lekarzem
      link: /pl
    profilePhoto: /img/jedrzej-lewandowski-600.jpg
    profileText: 'Cześć, jestem Jędrzej. Student 6 roku medycyny, programista senior fullstack (typescript / vue / node / golang). Ten blog jest moją kroniką.'
    weight: 2
    author: Jędrzej B. Lewandowski
    params:
      footer: |
        Copyright &copy; 2020-now by Jędrzej Lewandowski. <br />
        <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
        Made with [Hugo](https://gohugo.io/).
      monthNames:
        1: stycznia
        2: lutego
        3: marca
        4: kwietnia
        5: maja
        6: czerwca
        7: lipca
        8: sierpnia
        9: września
        10: października
        11: listopada
        12: grudnia
      menuMain:
        - identifier: blog
          title: "Blog"
          url: "/"
        - identifier: cv
          title: "CV"
          url: "/cv"
        - identifier: contact
          title: "Kontakt"
          url: "/contact"

  en:
    languageName: English
    title: Jędrzej Lewandowski (J-J) — software developer and medical student
    header:
      supertitle: Curious case of
      midtitle1: Jędrzej (J-J)
      midtitle2: Lewandowski
      subtitle: MDoctorist, programmist & behaviourist
      link: /en
    author: JB Lewandowski
    profilePhoto: /img/jedrzej-lewandowski-600.jpg
    profileText: 'Hi, I’m Jędrzej. 6th year medical student, fullstack software developer and behavioural design passionate. This blog is a chronicle of my activity.'
    weight: 1
    params:
      footer: |
        Copyright &copy; 2020-now by Jędrzej Lewandowski. <br />
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Licencja Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><br />Ten utwór jest dostępny na <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">licencji Creative Commons Uznanie autorstwa-Na tych samych warunkach 4.0 Międzynarodowe</a>.
        Made with [Hugo](https://gohugo.io/).
      monthNames:
        1: january
        2: february
        3: march
        4: april
        5: may
        6: june
        7: july
        8: august
        9: september
        10: october
        11: november
        12: december
      menuMain:
        - identifier: blog
          title: "Blog"
          url: "/"
        - identifier: cv
          title: "CV"
          url: "/cv"
        - identifier: contact
          title: "Contakt"
          url: "/contact"

permalinks:
  posts: /:year/:month/:title/
  archiveyearly: /:year/

imaging:
  quality: 99

params:
  description: Blog of Jędrzej (pronounce J-J) Lewandowski. Doctor, software developer and behaviorist.
  homeMetaContent: Blog of Jędrzej (pronounce J-J) Lewandowski. Doctor, software developer and behaviorist.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  mobileMediaBreakpoint: 768px

menu:
  categories:
    - identifier: bezpieczenstwo
      title: "Bezpieczeństwo (PL)"
      url: /pl/category/bezpieczenstwo
    - identifier: administracja
      title: Administracja (PL)
      url: /pl/category/administracja
    - identifier: elektronika
      title: Elektronika (PL)
      url: /pl/category/elektronika
    - identifier: fun
      title: Fun (PL)
      url: /pl/category/fun
    - identifier: inne
      title: Inne (PL)
      url: /pl/category/inne
    - identifier: java
      title: Java (PL)
      url: /pl/category/java
    - identifier: programowanie
      title: Programowanie (PL)
      url: /pl/category/programowanie
    - identifier: webmastering
      title: Webmastering (PL)
      url: /pl/category/webmastering
    - identifier: blockchain
      title: Blockchain (PL)
      url: /pl/category/blockchain
    - identifier: katolicyzm
      title: Katolicyzm (PL)
      url: /pl/category/katolicyzm
    - identifier: polski
      title: Polski (PL)
      url: /pl/category/polski
    - identifier: technologia
      title: Technologia (PL)
      url: /pl/category/technologia

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2