name: Jędrzej Lewandowski CV
title: "Jędrzej Lewandowski: medical student and software developer"
email: jedrzejblew@gmail.com
description: "Full stack software developer/architect and medical student. Typescript, Vue, Node.js, Java SE, Blockchain, cloud. My curriculum vitae and projects."
url: ""
baseurl: "/"

# Build settings
markdown: kramdown
include: ["_pages"]

## Front matter defaults
defaults:

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed
# Prayer:
#  Gloria Patri, et Filio, et Spiritui Sancto, sicut erat in principio et nunc et semper et in saecula
#  saeculorum. Amen. In te, Domine, speravi: non confundar in aeternum.
